name: brat_mcp
description: An MCP Server for Llama CPP.
version: 1.0.8

environment:
  sdk: ^3.11.5


dependencies:
  args: ^2.7.0
  dio: ^5.9.2
  html: ^0.15.6
  path: ^1.9.0
  puppeteer: ^3.22.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
